from datetime import datetime
import uuid


def get_current_datetime() -> str:
    """
    @return:
        str: current datetime in this format:
        MM-DD-YYYY--HH-MM
    """

    return datetime.now().strftime('%m-%d-%Y--%H-%M')


def generate_unique_id() -> str:
    """
    @return:
        str: a unique id generated by uuid4()
    """
    return str(uuid.uuid4())


def create_new_filename(uploaded_filename: str) -> str:
    """
    @summary:
        Creates a new filename for the uploaded file.
    @param:
        uploaded_filename: str
            The filename of the uploaded file.
    @return:
        str: the new filename in this format:
        original_filename__MM-DD-YYYY--HH-MM__unique_id.pptx
    """
    # remove the extension from the filename
    uploaded_filename = uploaded_filename.split('.')[0]
    return f'{uploaded_filename}__{get_current_datetime()}__{generate_unique_id()}.pptx'


def get_unique_id(output_filename: str) -> str:
    """
    @summary:
        Returns the unique id from the output filename.
    @param:
        output_filename: str
            The filename of some output json file.
    @return:
        str: the unique id from the output filename.
    """
    # remove the extension from the filename
    uploaded_filename = output_filename.split('.')[0]
    return uploaded_filename.split('__')[-1]


def get_uploaded_datetime(output_filename: str) -> str:
    """
    @summary:
        Returns the datetime from the output filename.
    @param:
        output_filename: str
            The filename of some output json file.
            the format of the filename is:
            original_filename__MM-DD-YYYY--HH-MM__unique_id.pptx
    @return:
        str: the datetime from the output filename.
        example:
            original_filename__01-01-2021--12-00__xxx-yyy-zzz.json ->
            01-01-2021 12-00
    """
    timedate = output_filename.split('__')[-2]  # MM-DD-YYYY--HH-MM
    date = timedate.split('--')[0]  # MM-DD-YYYY
    time = timedate.split('--')[1].replace('-', ':')  # HH:MM
    return f'{date} {time}'  # MM-DD-YYYY HH:MM


def get_original_filename(output_filename: str) -> str:
    """
    @summary:
        Returns the original filename from the output filename.
    @param:
        output_filename: str
            The filename of some output json file.
    @return:
        str: the original filename from the output filename.
    """
    file_name_parts = output_filename.split('__')[:-2]
    return ''.join(file_name_parts)
